version: "2.1"

services:
  node:
    container_name: restaurant-reviews-app
    image: restaurant-reviews-i
    build:
      context: .
      dockerfile: ./.docker/node.dev.dockerfile
    ports:
      - "7000:7000"
      - "5858:5858"
    networks:
      - restaurantreviews-network
    volumes:
      - .:/var/app
    env_file:
      - ./.docker/env/app.dev.env
    working_dir: /var/app

  mongo:
    container_name: restaurantreviews-network-mongodb
    image: mongo:3.4.1
    build:
      context: .
      dockerfile: ./.docker/mongo.dev.dockerfile
    env_file:
      - ./.docker/env/mongo.dev.env
    networks:
      - restaurantreviews-network
    ports:
      - "27017"

networks:
  restaurantreviews-network:
    driver: bridge